### ISSUE TITLE
[Feature request] Change backgroundColor while sliding

### ISSUE THREAD

**Issue by XinyueZ** [Friiiis/slide_to_confirm#3]
I need to know how to change backgroundColor while I am sliding with "dragging" the element.

Maybe can give some suggestions.

**Comment by Friiiis** [comment]
What is your desired behaviour? Do you want the background color to gradually change while you slide?

**Comment by XinyueZ** [comment]
yes, and currently I just copy your code and adjust for my project.
however, really like to see some official work from this repo.

behaviour:

1. sliding.
2. the range was passed shall be other color.
