### ISSUE TITLE
Let it on the right side when it drags

### ISSUE THREAD

**Issue by Liliana99** [Friiiis/slide_to_confirm#5]
Congratulations  to nice job!!

I would like it stay on right side when I drags it from  left side to right side?

**Comment by Friiiis** [comment]
Thank you :)
At the moment this will not be possible, but you are more than welcome to make the changes yourself and put them in a pull request.

**Comment by jonatascm** [comment]
Just added PR with the param to stick the cursor at end of slide
@Friiiis 
👍
